name: Update data

on:
  push:
    branches:
      - master
    paths:
      - 'static/data/**'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update data
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.BUCKET_REGION }}
        BUCKET: ${{ secrets.BUCKET_NAME }}
      run: ./deploy-data.sh
